--
-- PostgreSQL database dump
--

\restrict g9j9gLccfLU3kWLA9WFWTLZ7xG3Ek5tcRxwEcEulUowIgjFedckuCgcD9ydNXzz

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_appointment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings_appointment (
    id bigint NOT NULL,
    client_name character varying(100) NOT NULL,
    client_phone character varying(20) NOT NULL,
    client_email character varying(254) NOT NULL,
    client_address text NOT NULL,
    service character varying(20) NOT NULL,
    duration integer NOT NULL,
    addon character varying(20) NOT NULL,
    zone character varying(10) NOT NULL,
    appointment_date date NOT NULL,
    appointment_time time without time zone NOT NULL,
    status character varying(30) NOT NULL,
    masseuse_departure_time time without time zone,
    total_price integer NOT NULL,
    notes text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    payment_method character varying(10),
    preferred_pressure character varying(10),
    client_package_id bigint,
    preferred_service character varying(50) NOT NULL
);


--
-- Name: bookings_appointment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings_appointment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_appointment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bookings_clientpackage; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings_clientpackage (
    id bigint NOT NULL,
    client_name character varying(100) NOT NULL,
    client_phone character varying(20) NOT NULL,
    package_type character varying(20) NOT NULL,
    total_sessions integer NOT NULL,
    sessions_completed integer NOT NULL,
    purchase_date date NOT NULL,
    expiry_date date,
    is_active boolean NOT NULL
);


--
-- Name: bookings_clientpackage_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings_clientpackage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_clientpackage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add appointment	7	add_appointment
26	Can change appointment	7	change_appointment
27	Can delete appointment	7	delete_appointment
28	Can view appointment	7	view_appointment
29	Can add client package	8	add_clientpackage
30	Can change client package	8	change_clientpackage
31	Can delete client package	8	delete_clientpackage
32	Can view client package	8	view_clientpackage
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1200000$KiiC2AsaZUDV0jf1bQ91vI$d1KYCaaePi7HLCBKnMMYIjkUFgYt/DB1TzoyFUPN8hs=	2026-06-25 07:04:45.86239+00	t	rosette				t	t	2026-06-25 07:03:54.765215+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: bookings_appointment; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bookings_appointment (id, client_name, client_phone, client_email, client_address, service, duration, addon, zone, appointment_date, appointment_time, status, masseuse_departure_time, total_price, notes, created_at, payment_method, preferred_pressure, client_package_id, preferred_service) FROM stdin;
13	T-Mak	+961 76 768 016		Aykon Tower C\r\nApt 1614	deep_tissue	90	none	zone1	2026-06-25	14:00:00	completed	13:00:00	370	                        Nil	2026-06-23 21:46:37.925441+00	card	medium	\N	
11	Sebastian 	+971 58 541 9841		Maze Tower\r\nApt 3207	deep_tissue	90	none	zone1	2026-06-26	10:00:00	completed	09:00:00	370	                        Nil	2026-06-23 21:32:13.246933+00	card	firm	\N	
59	Marius	+971502139132		395 Sheikh Zayed Road,\r\nDamac Maison Aykon City Tower B\r\nApartment 4013\r\n40th floor	deep_tissue	90	none	zone1	2026-07-02	10:00:00	completed	09:00:00	370	                        	2026-07-01 19:16:53.754463+00	cash	firm	\N	
1	T Mak	+97176768016			signature	90	none		2026-06-22	14:00:00	completed	13:00:00	0		2026-06-21 20:55:45.008783+00	\N	\N	\N	
48	Samak	+971502435934		Damac Ghalia\r\nApt 2019	signature	90	none	zone2	2026-06-30	17:00:00	completed	16:00:00	345	 Lower back pain                       	2026-06-29 15:53:38.120528+00	cash	firm	\N	
56	Mariam	+971509120708	maru.malafeeva@gmail.com	Executive residence 2 (802)	swedish	60	none	zone2	2026-06-30	20:00:00	completed	19:00:00	275	                        	2026-06-30 12:54:24.971621+00	cash	medium	\N	
7	Mariam	+971509120708		Executive residence 2	swedish	60	none	zone2	2026-06-22	21:00:00	completed	20:00:00	275	                        	2026-06-22 07:35:50.115413+00	\N	\N	\N	
67	Aleksandr Partanen	+971506670386		Damac Hills , Pelham, Villa 213	signature	90	none	other	2026-07-05	10:30:00	confirmed	09:30:00	320	                        	2026-07-04 07:57:58.297224+00	card	light	\N	
9	Ahmed Samak	502435934		Damac ghalia	swedish	90	none	zone2	2026-06-23	17:00:00	completed	16:00:00	345	                        Lower back pain	2026-06-23 05:50:56.210121+00	cash	medium	\N	
49	Alina Kamalieva	+971569703615	alinakamalieva01@gmail.com	Socio tower 2, dubai hills estate , 515 apartment 	swedish	60	none	other	2026-07-01	20:30:00	completed	19:30:00	250	                        	2026-06-29 16:58:05.541304+00	card	medium	\N	
66	Rosette Chebukwa Wafula	+971505389174		Oval tower	deep_tissue	120	none	zone1	2026-07-04	15:30:00	cancelled	14:30:00	450	                        Nil	2026-07-04 07:40:40.887278+00	cash	firm	\N	
65	Rosette Chebukwa Wafula	+971503689174			swedish	120	none		2026-07-04	12:30:00	completed	11:30:00	0		2026-07-04 07:38:39.429089+00	\N	\N	\N	
14	Jake Nazer	+971 55 154 9956		Um suqeim \r\nRahaal2\r\nApt 501	swedish	90	none	other	2026-06-24	15:00:00	completed	14:00:00	320	                        Nil	2026-06-24 08:19:00.111855+00	cash	medium	\N	
12	Alina	+971 56 970 3615		Collective Tower 1\r\nApt 313	swedish	60	none	zone2	2026-06-24	21:00:00	completed	20:00:00	275	                        Nil	2026-06-23 21:40:39.557143+00	card	medium	\N	
62	Sébastien	+971585419841		Flat 3207, Maze Tower, DIFC	deep_tissue	90	none	zone1	2026-07-03	11:00:00	completed	10:00:00	370	                        None	2026-07-02 12:00:49.325323+00	card	firm	\N	
51	Noor Kerdi	+971522281311	noormkerdi@gmail.com	Villa 35, street 14A, Jumeirah 2	sports	90	none	zone1	2026-07-01	18:30:00	completed	17:30:00	380	                        Slipped discs L5 and L6	2026-06-29 17:28:25.79376+00	card	medium	\N	
50	Batool kerdi	+971582166618	batoolku@gmail.com	35 14a street jumeirah 2 	sports	90	none	other	2026-07-01	20:00:00	completed	19:00:00	380	     Back pain                    	2026-06-29 16:58:27.9835+00	cash	medium	\N	
21	Eduardo Herrero	+971547524178			sports	90	none		2026-06-26	18:00:00	completed	\N	0		2026-06-26 13:05:05.159739+00	\N	\N	\N	
63	Ahmed Moukhtar	+971528148841	amazhary@icloud.com	Apartment 404, building Noor 5, Midtown, IMPZ Dubai Production City	deep_tissue	90	none	zone2	2026-07-03	17:00:00	completed	16:00:00	395	                        	2026-07-02 13:18:25.169296+00	card	firm	\N	
55	Irina	+971554428835	postofficemail5@gmail.com	Lofts Central 2301 	swedish	90	none	zone1	2026-07-05	12:00:00	cancelled	11:00:00	320	                        	2026-06-30 11:06:24.245974+00	cash	medium	\N	
64	Aleksandr Partanen	+971506670386			signature	90	none		2026-07-04	11:30:00	declined	10:30:00	0		2026-07-04 06:20:56.36489+00	\N	\N	\N	
68	Jeremy Mansour	+971556796098		Al Noor Tower by Ansari	signature	90	none	zone1	2026-07-05	13:00:00	confirmed	12:00:00	320	                        	2026-07-04 12:27:15.373905+00	cash	firm	\N	
\.


--
-- Data for Name: bookings_clientpackage; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bookings_clientpackage (id, client_name, client_phone, package_type, total_sessions, sessions_completed, purchase_date, expiry_date, is_active) FROM stdin;
2	Test	+971352234531	monthly_wellness	5	0	2026-06-26	2026-07-27	t
3	test 1	+971501234533	monthly_wellness	5	5	2026-06-29	2026-07-31	f
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-06-25 07:10:43.842737+00	16	Test — Swedish Massage on 2026-06-25 at 13:10:03	1	[{"added": {}}]	7	1
2	2026-06-25 07:11:49.246186+00	1	Test — Monthly Wellness (1/5)	1	[{"added": {}}]	8	1
3	2026-06-25 09:16:51.257441+00	16	Test — Swedish Massage on 2026-06-25 at 13:10:03	2	[{"changed": {"fields": ["Preferred pressure", "Payment method"]}}]	7	1
4	2026-06-26 07:12:14.854548+00	17	test 2 — VIP Wellness Package on 2026-06-27 at 18:00:00	1	[{"added": {}}]	7	1
5	2026-06-26 08:17:45.794784+00	1	Test — Monthly Wellness (1/5)	3		8	1
6	2026-06-26 08:20:37.657206+00	2	martha muronji — Signature Full Body Reset on 2026-06-22 at 11:00:00	3		7	1
7	2026-06-26 08:20:37.657269+00	5	Martha Muronji — Swedish Massage on 2026-06-22 at 12:30:00	3		7	1
8	2026-06-26 08:20:37.657295+00	6	Martha Muronji — Thai Massage on 2026-06-22 at 15:30:00	3		7	1
9	2026-06-26 08:20:37.657311+00	4	Valentine Masicha  — Thai Massage on 2026-06-22 at 18:00:00	3		7	1
10	2026-06-26 08:20:37.657324+00	8	Martha Muronji — Deep Tissue Massage on 2026-06-22 at 22:00:00	3		7	1
11	2026-06-26 08:20:37.657338+00	10	Martha Muronji — Thai Massage on 2026-06-23 at 15:00:00	3		7	1
12	2026-06-26 08:20:37.657353+00	16	Test — Swedish Massage on 2026-06-25 at 13:10:03	3		7	1
13	2026-06-26 08:20:37.657373+00	15	wafula — Monthly Wellness Package on 2026-06-27 at 11:00:00	3		7	1
14	2026-06-26 08:20:37.657388+00	18	test 3 — Monthly Wellness Package on 2026-06-27 at 13:30:00	3		7	1
15	2026-06-26 08:20:37.657403+00	17	test 2 — VIP Wellness Package on 2026-06-27 at 18:00:00	3		7	1
16	2026-06-26 13:34:47.54475+00	19	test 1 — Deep Tissue Massage on 2026-06-27 at 16:00:00	3		7	1
17	2026-06-26 13:34:47.544789+00	20	Test — Monthly Wellness Package on 2026-06-27 at 18:00:00	3		7	1
18	2026-06-26 13:59:03.828575+00	22	Test — Monthly Wellness Package on 2026-06-27 at 18:00:00	3		7	1
19	2026-06-26 18:42:43.116994+00	23	test 2 — Deep Tissue Massage on 2026-06-27 at 10:30:00	3		7	1
20	2026-06-27 10:33:33.104858+00	24	test 2 — Deep Tissue Massage on 2026-06-27 at 10:30:00	3		7	1
21	2026-06-27 10:33:33.104923+00	26	test 4 — Hot Stone Massage on 2026-06-27 at 14:30:00	3		7	1
22	2026-06-27 10:33:33.104952+00	25	test 2 — Hot Stone Massage on 2026-06-27 at 19:00:00	3		7	1
23	2026-06-27 10:50:37.674488+00	27	Test — Hot Stone Massage on 2026-06-27 at 21:00:00	3		7	1
24	2026-06-27 11:15:20.670057+00	29	Test — Thai Massage on 2026-06-27 at 21:00:00	3		7	1
25	2026-06-27 11:15:20.670104+00	28	Test — Hot Stone Massage on 2026-06-27 at 21:00:00	3		7	1
26	2026-06-27 11:31:53.251336+00	30	Test — Sports Massage on 2026-06-27 at 21:00:00	3		7	1
27	2026-06-27 19:39:33.183477+00	31	Test — Sports Massage on 2026-06-27 at 21:00:00	3		7	1
28	2026-06-29 07:03:44.292063+00	33	test 1 — Deep Tissue Massage on 2026-06-27 at 19:00:00	3		7	1
29	2026-06-29 07:03:44.292102+00	32	wafula — Deep Tissue Massage on 2026-06-27 at 20:30:00	3		7	1
30	2026-06-29 07:03:44.29212+00	35	test 1 — Sports Massage on 2026-06-28 at 20:30:00	3		7	1
31	2026-06-29 07:51:22.061287+00	36	Testing — Swedish Massage on 2026-06-29 at 21:00:00	3		7	1
32	2026-06-29 08:25:08.26418+00	34	Martha — Swedish Massage on 2026-06-27 at 18:30:00	3		7	1
33	2026-06-29 08:25:08.264228+00	37	Test — Deep Tissue Massage on 2026-06-30 at 21:00:00	3		7	1
34	2026-06-29 08:25:08.264248+00	38	test 1 — Monthly Wellness Package on 2026-07-01 at 15:00:00	3		7	1
35	2026-06-29 08:46:41.725796+00	41	test 1 — Hot Stone Massage on 2026-06-29 at 14:00:00	3		7	1
36	2026-06-29 08:46:41.72588+00	40	test 1 — Sports Massage on 2026-06-29 at 17:30:00	3		7	1
37	2026-06-29 09:02:28.244744+00	47	test 1 — Sports Massage on 2026-06-29 at 16:30:00	3		7	1
38	2026-06-29 09:02:28.244844+00	45	test 1 — Thai Massage on 2026-06-29 at 17:00:00	3		7	1
39	2026-06-29 09:02:28.244881+00	44	test 1 — Deep Tissue Massage on 2026-06-29 at 17:00:00	3		7	1
40	2026-06-29 09:02:28.244908+00	46	test 1 — Signature Full Body Reset on 2026-06-29 at 18:30:00	3		7	1
41	2026-06-29 09:02:28.244929+00	43	Test — Deep Tissue Massage on 2026-06-30 at 17:00:00	3		7	1
42	2026-06-29 09:02:28.244949+00	42	test 1 — Monthly Wellness Package on 2026-07-01 at 15:00:00	3		7	1
43	2026-06-29 09:02:28.244968+00	39	test 1 — Monthly Wellness Package on 2026-07-01 at 15:00:00	3		7	1
44	2026-06-29 17:31:17.822732+00	52	wafula — Hot Stone Massage on 2026-06-29 at 21:00:00	3		7	1
45	2026-06-29 17:37:10.416657+00	53	test 3 — Hot Stone Massage on 2026-06-29 at 21:00:00	3		7	1
46	2026-06-29 17:37:10.416715+00	54	test 2 — Swedish Massage on 2026-06-30 at 19:30:00	3		7	1
47	2026-07-01 09:50:28.364082+00	57	Test — Signature Full Body Reset on 2026-07-02 at 18:30:00	3		7	1
48	2026-07-01 09:50:28.364122+00	58	Test — Deep Tissue Massage on 2026-07-09 at 11:00:00	3		7	1
49	2026-07-02 06:37:08.793947+00	3	Rosette Chebukwa Wafula — Swedish Massage on 2026-06-23 at 10:30:00	3		7	1
50	2026-07-02 06:43:57.914625+00	60	Test — Thai Massage on 2026-07-02 at 19:30:00	3		7	1
51	2026-07-02 07:03:29.81836+00	61	Test — Deep Tissue Massage on 2026-07-02 at 17:00:00	3		7	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	bookings	appointment
8	bookings	clientpackage
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-06-21 20:48:32.650096+00
2	auth	0001_initial	2026-06-21 20:48:32.674879+00
3	admin	0001_initial	2026-06-21 20:48:32.683545+00
4	admin	0002_logentry_remove_auto_add	2026-06-21 20:48:32.687198+00
5	admin	0003_logentry_add_action_flag_choices	2026-06-21 20:48:32.690859+00
6	contenttypes	0002_remove_content_type_name	2026-06-21 20:48:32.697942+00
7	auth	0002_alter_permission_name_max_length	2026-06-21 20:48:32.702536+00
8	auth	0003_alter_user_email_max_length	2026-06-21 20:48:32.708157+00
9	auth	0004_alter_user_username_opts	2026-06-21 20:48:32.726737+00
10	auth	0005_alter_user_last_login_null	2026-06-21 20:48:32.731595+00
11	auth	0006_require_contenttypes_0002	2026-06-21 20:48:32.733132+00
12	auth	0007_alter_validators_add_error_messages	2026-06-21 20:48:32.736923+00
13	auth	0008_alter_user_username_max_length	2026-06-21 20:48:32.742449+00
14	auth	0009_alter_user_last_name_max_length	2026-06-21 20:48:32.746342+00
15	auth	0010_alter_group_name_max_length	2026-06-21 20:48:32.751786+00
16	auth	0011_update_proxy_permissions	2026-06-21 20:48:32.755263+00
17	auth	0012_alter_user_first_name_max_length	2026-06-21 20:48:32.762622+00
18	bookings	0001_initial	2026-06-21 20:48:32.766004+00
19	bookings	0002_alter_appointment_status	2026-06-21 20:48:32.769521+00
20	bookings	0003_alter_appointment_status	2026-06-21 20:48:32.772477+00
21	sessions	0001_initial	2026-06-21 20:48:32.778236+00
22	bookings	0004_appointment_payment_method_and_more	2026-06-23 11:15:58.486618+00
23	bookings	0005_alter_appointment_service_alter_appointment_zone	2026-06-24 09:05:39.074195+00
24	bookings	0006_clientpackage_alter_appointment_service_and_more	2026-06-25 06:47:21.904018+00
25	bookings	0007_appointment_preferred_service	2026-06-26 08:05:25.492079+00
26	bookings	0008_alter_appointment_preferred_service	2026-06-26 08:05:25.507758+00
27	bookings	0009_alter_appointment_status	2026-06-29 06:40:00.441325+00
28	bookings	0010_alter_appointment_status	2026-06-29 06:40:00.449066+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
g28fmpbm91ilblfj1yzwtee8zfg9ct2l	.eJxVzkEKwjAQheGryGy1kEkxjb2C4BVCbKcabDNlEtyU3t1GROj6--G9BWahIYyji34iaOHGLIcrSR_g9Lf5ybHg8dLgWWttsUbcvBsDxbxnq9EYg3bjO_MrxIcbWCbX--yhXSCRvENX8jSz5PSbIRHqS1REK20q1VQKd5rD9yLatlawrh8WEjsZ:1weFmT:U1_22vNjR46B-2Fnln3QCK9FHxSLHsIxJIQc3EOobb8	2026-07-13 17:28:25.808771+00
ktv3jtmluxwg55v045bkf14skqu9r2qb	.eJyrViooSk3LzMmJz0vMTVWyUnJNKU0sSslX8EgtKkotylfSgSsoyMjPA6nQtjQ3NDUxNzUyMTS3AMon52Sm5pXgkK4FADOlHe0:1wd6KE:JGsyUC-8TslKnu33LHHLGmFYYJsjH3SH9YzUEWzWzxY	2026-07-10 13:10:30.866781+00
42sy91cb2uwlhq2sergsrpid1edtylp5	eyJwZW5kaW5nX2FwcG9pbnRtZW50X2lkIjo0LCJtYXNzZXVzZV9hdXRoZW50aWNhdGVkIjp0cnVlfQ:1wbRZh:VgOV_9YOHvgy_Acy9B8EpdL_KhsdieOEY8wo3GXNHnU	2026-07-05 23:27:37.401474+00
kxlx3hp01ei8ljcn4qmnvgv9ycxbwpss	.eJyrVkrOyUzNK4kvyMjPS1WyUtK2NDc0NTIysjA0NjRU0lEqKEpNy8zJic9LzAVJ--XnFyl4pxalZCLJYddbCwA1Exu7:1weGRP:xR32dTAmEAFWSFw0JOvaPXSe_VwNZ7bh2Lk0F3bc6hQ	2026-07-13 18:10:43.857492+00
f81jxeqiqfqhhcozmkbrf7m6vmaf6akt	.eJyrViooSk3LzMmJz0vMTVWyUnLMSc0uTsxLKVIISCwqScxLzVPSgaspyMjPAynStjQ3NDUwMzM3MLYwA8on52Sm5pXgkK4FAKdsHxw:1wfvIX:1ukmZ1aLWFLFiM1WOlW5pNtiTT-0VYI3p11Fsv-8V6g	2026-07-18 08:00:25.906893+00
rjsz1lj4a3adshax7kvvpguaq3f3n2ca	.eJx1kL1uwyAURt-FtYllsDHgMXu37oif65jGBgtwlyjvXrA8NEMnpO-c-3HhiTbw1vm7VNsWnM8r-CydRSO5oFWlBHsCqfY8l9wZlaGgHHe4oCOVBcfDRxi9ZVqZR6kuwH4rfw-NCT5Hp5uqNCdNzWewsNxO961gVmku00J1g8CkZRPnk-AWDBv6nmPQilM6ELDYctqZXgjGp54SrGnfDbwchFimS6lZXH3VNgcPpfFDMExbTLqeclbwFmFyyyK9Wiv-gpT_pP9N6RAe9d-mEFdpVVZofKKy948zVU9biDmdPRAj2CpVQloyXNvhSsQbze64HbOxa9Hr9QuCfoSv:1wfvPd:0tkWH0ORrsTbxL69LrrgvnZVH8e7VCjYSWcGUDK3UvM	2026-07-18 08:07:45.06424+00
dbdlgccfi1limkkqfznzwta7zzef2lxg	eyJtYXNzZXVzZV9hdXRoZW50aWNhdGVkIjp0cnVlfQ:1wbi11:IxednOcmmNqiW2ZAA3vRysQ9atMqRvE_czb6w6fSnmM	2026-07-06 17:00:55.66318+00
0jfx7cp048dymirvc53q8vapwglty14z	.eJyrViooSk3LzMmJz0vMTVWyUvJNLMpMzFXSgYsXZOTngSS0Lc0NTQ0sDY0MzA0sgPLJOZmpeSU4pGsB-jIacw:1weY42:IhezVJ3nKeHZHQbBa9I6mRgfkmTAAZbCqJa2JdJ9-Ag	2026-07-14 12:59:46.599856+00
fkun9mfro2889e9pac1lyg03u09zty3s	.eJx1jjEOwjAQBL-CriVIDgQCafkBDaV1xBdyIrEt-0yKiL-DEQUUlKtZ7c4Mnqxhe9XovWMrI1nRbKApqwLagXP0vbMEDSwPdblV283-UNYVFOADdTwM2uKY8clFEqHFsadLuk24OGOXBvwq_hsaMUZKkTQm6V-P3KLQy0FCogIuzt2yYefCqA0KQjNDpHDnNo_FiQzH_nNDIZDJrYzWar1bqXqlqh8q_PYt981GwePxBIRxVjs:1wg0Pa:X8wc-jn6AD5luPlMn_hqEMSghjtdODeTulTMcOJnMX4	2026-07-18 13:28:02.318485+00
wgg194dvqvnxe69cr26qiydzuwpitkgp	.eJyrViooSk3LzMmJz0vMTVWyUvJKLUrNrVTwTcwrzi8tUtKByxdk5OeBFGhbmhuampqZW5oZWFoA5ZNzMlPzSnBI1wIAF7Mduw:1wg2dj:l5PVI-SO0RR7MB1Pj7RUwoZIqpTcZV2EkkwVPG19MH8	2026-07-18 15:50:47.313828+00
o02t4xc7wca3xvncvzdok6lwnqlehm5q	.eJxNzT0OgzAMQOG7eC1DyU8juExkgSmWEhMRRx2q3r1hatf3De8NhWRleUYs5WDRTKKRV5hHP0DGWqlVith078ALKnXTs9EA5aSNU4qCmWCGF24tIfx62Q-54DaFcXp4Z4NxpvuS-Jr8s78bY523AT5fDbcwZg:1wezl7:Ct1PjU1HNJn-PCRlT6WgHTPHXtHIeoFQ0gjtngI-7Qg	2026-07-15 18:34:05.437485+00
sf6wowqj7kkpfua3n909e341hdpuwrc7	.eJyrViooSk3LzMmJz0vMTVWyUvJNLMosLVbSgYsXZOTngSS0Lc0NTQ2MDI0tDY2NgPLJOZmpeSU4pGsBAAMagQ:1wf0eY:XFTUmp0ZbHWad01p2YMalCkwi_EEhrWryZWu3C0GQ7s	2026-07-15 19:31:22.347564+00
z85vrso5hivpp6op2hi9uqwmjpbyvij7	.eJyrVkrOyUzNK4kvyMjPS1WyUtK2NDc0NbM0NzA2MzRV0lEqKEpNy8zJic9LzAVJO-Zk5iUqeCfmJgK1lSUiKcBuQC0A2gsdwA:1weFP8:ASE3rlq0x0ZgZN_d09wdJmx76t9KkyuWPh5ZrClyEQ4	2026-07-13 17:04:18.811155+00
qyrmz4nrqgnvofatlysipsiq4mcwbd0y	.eJyrViooSk3LzMmJz0vMTVWyUgqOKTUwSLVMSiwuyUzNU9KByxdk5OeBFGhbmhuaWpiaGFpamBgC5ZNzgOpKcEjXAgD3gx0-:1wfG8K:EZhbckM0qcf5htfjJ7lgl8hocz4sfQ8JqU2G9PoSke4	2026-07-16 12:03:08.569609+00
lrhtwc6tvziicoq9jv0fivgqmq46rvp1	eyJwcmVmaWxsX25hbWUiOiJBaG1lZCBNb3VraHRhciIsInByZWZpbGxfcGhvbmUiOiIrOTcxNTI4MTQ4ODQxIn0:1wfHJB:VFSKDxJC3y2Q6JLCizRXFjrilXt2p0iDJczak7PmiRQ	2026-07-16 13:18:25.189464+00
gqlxhhmzzapqjvmcei71c3jlu28w8uen	.eJyrVkrOyUzNK4kvyMjPS1WyUtK2NDc0NbIwNLGwMDFU0lEqKEpNy8zJic9LzAVJO2bkpqYo-OaXZmeUJBYhyWPXXwsAvK8deA:1wfY9R:xoIBEhkCKMPGga6m-wIkYD4X5wLrnqJxggkteZ9Qvo0	2026-07-17 07:17:29.822953+00
gqx2nltkto57igq3wwazsnx5i7itw9qs	.eJyrViooSk3LzMmJz0vMTVWyUvIsysxLVNKBCxdk5OeBxLUtzQ1NTU1MjCwsjE2B8sk5mal5JTikawHaqhon:1wfYsY:qvfD_82Qy_uE1aDY4D95RpYe44QuK8_CkhN10dql3qQ	2026-07-17 08:04:06.108863+00
xw2rhoydgauza00l2mi4r9mxz7kx7ypo	.eJyrViooSk3LzMmJz0vMTVWyUgpJLS7JzEtX0oFLFGTk54FktC3NDY1MLUxMDE3NzIDyuYnFxamlxanxiaUlGal5JZnJiSWpKUpWJUWlqbUALfkeEw:1wfaBa:LbCnMs2IxJqsTY3qobByoRABStmOfnyVTzBraoLPGoA	2026-07-17 09:27:50.87776+00
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 32, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: bookings_appointment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bookings_appointment_id_seq', 68, true);


--
-- Name: bookings_clientpackage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bookings_clientpackage_id_seq', 3, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 51, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 8, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 28, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: bookings_appointment bookings_appointment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings_appointment
    ADD CONSTRAINT bookings_appointment_pkey PRIMARY KEY (id);


--
-- Name: bookings_clientpackage bookings_clientpackage_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings_clientpackage
    ADD CONSTRAINT bookings_clientpackage_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: bookings_appointment_client_package_id_b1bad752; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX bookings_appointment_client_package_id_b1bad752 ON public.bookings_appointment USING btree (client_package_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: bookings_appointment bookings_appointment_client_package_id_b1bad752_fk_bookings_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings_appointment
    ADD CONSTRAINT bookings_appointment_client_package_id_b1bad752_fk_bookings_ FOREIGN KEY (client_package_id) REFERENCES public.bookings_clientpackage(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict g9j9gLccfLU3kWLA9WFWTLZ7xG3Ek5tcRxwEcEulUowIgjFedckuCgcD9ydNXzz

