# Generated by Django 6.0.6 on 2026-06-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_address', models.TextField()),
                ('service', models.CharField(choices=[('signature', 'Signature Full Body Reset'), ('swedish', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('sports', 'Sports Massage'), ('hot_stone', 'Hot Stone Massage'), ('thai', 'Thai Massage')], max_length=20)),
                ('duration', models.IntegerField(choices=[(60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')])),
                ('addon', models.CharField(choices=[('none', 'No Add-On'), ('foot_30', 'Foot Massage — 30 min (120 AED)'), ('hns_30', 'Head, Neck & Shoulders — 30 min (100 AED)'), ('hns_60', 'Head, Neck & Shoulders — 60 min (180 AED)')], default='none', max_length=20)),
                ('zone', models.CharField(choices=[('zone1', 'Zone 1 — Business Bay, Downtown, DIFC, City Walk, Al Safa'), ('zone2', 'Zone 2 — JVC, Arjan, Motor City, Dubai Hills Estate'), ('zone3', 'Zone 3 — Marina, JBR, Palm Jumeirah, Jumeirah Golf Estates')], max_length=10)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('masseuse_departure_time', models.TimeField(blank=True, null=True)),
                ('total_price', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
