# Generated by Django 6.0.6 on 2026-06-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferred_pressure',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('firm', 'Firm')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zone',
            field=models.CharField(blank=True, choices=[('zone1', 'Zone 1 — Business Bay, Downtown, DIFC, City Walk, Al Safa'), ('zone2', 'Zone 2 — JVC, Arjan, Motor City, Dubai Hills Estate'), ('zone3', 'Zone 3 — Marina, JBR, Palm Jumeirah, Jumeirah Golf Estates'), ('other', 'My area is not listed')], max_length=10),
        ),
    ]
