# Generated by Django 6.0.6 on 2026-06-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_appointment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('signature', 'Signature Full Body Reset'), ('swedish', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('sports', 'Sports Massage'), ('hot_stone', 'Hot Stone Massage'), ('thai', 'Thai Massage'), ('monthly_wellness', 'Monthly Wellness Package — 5 × 90 min'), ('vip_wellness', 'VIP Wellness Package — 8 × 90 min')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zone',
            field=models.CharField(blank=True, choices=[('zone1', 'Zone 1 — Business Bay, Downtown, DIFC, City Walk, Al Safa'), ('zone2', 'Zone 2 — JVC, Arjan, Motor City, Dubai Hills Estate'), ('zone3', 'Zone 3 — Marina, JBR, Palm Jumeirah, Jumeirah Golf Estates'), ('other', 'Other — Contact via WhatsApp')], max_length=10),
        ),
    ]
