# Generated by Django 6.0.6 on 2026-06-25 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_appointment_service_alter_appointment_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('package_type', models.CharField(choices=[('monthly_wellness', 'Monthly Wellness'), ('vip_wellness', 'VIP Wellness')], max_length=20)),
                ('total_sessions', models.IntegerField()),
                ('sessions_completed', models.IntegerField(default=0)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('signature', 'Signature Full Body Reset'), ('swedish', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('sports', 'Sports Massage'), ('hot_stone', 'Hot Stone Massage'), ('thai', 'Thai Massage'), ('monthly_wellness', 'Monthly Wellness Package'), ('vip_wellness', 'VIP Wellness Package')], max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='bookings.clientpackage'),
        ),
    ]
