# Generated by Django 6.0.6 on 2026-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_clientpackage_alter_appointment_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_service',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
