# Generated by Django 6.0.6 on 2026-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_appointment_preferred_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='preferred_service',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
