# Generated by Django 6.0.6 on 2026-06-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_appointment_preferred_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('declined', 'Declined'), ('Cancelled', 'cancelled')], default='pending', max_length=10),
        ),
    ]
