# Generated by Django 6.0.6 on 2026-07-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_appointment_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpackage',
            name='package_type',
            field=models.CharField(choices=[('monthly_wellness', 'Rosette Wellness Membership'), ('vip_wellness', 'Rosette Wellness Membership - VIP')], max_length=20),
        ),
    ]
