# Generated by Django 6.0.6 on 2026-07-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_clientpackage_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('signature', 'Signature Full Body Reset'), ('swedish', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('sports', 'Sports Massage'), ('hot_stone', 'Hot Stone Massage'), ('monthly_wellness', 'Monthly Wellness Membership'), ('vip_wellness', 'Rosette Wellness Membership - VIP')], max_length=20),
        ),
    ]
