# Generated by Django 6.0.6 on 2026-07-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_alter_appointment_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('signature', 'Signature Full Body Reset'), ('swedish', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('sports', 'Sports Massage'), ('hot_stone', 'Hot Stone Massage'), ('monthly_wellness', 'Rosette Wellness Membership'), ('vip_wellness', 'Rosette Signature Membership')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='zone',
            field=models.CharField(blank=True, choices=[('zone1', 'Zone 1 — Business Bay, Downtown Dubai, DIFC, City Walk, Al Wasl, Jumeirah 1, Jumeirah 2, Al Satwa, Dubai Canal area'), ('zone2', 'Zone 2 — Dubai Hills Estate, Al Barsha, JVC, Arjan, Motor City, Dubai Science Park, Meydan, Nad Al Sheba, Jumeirah Islands, JLT'), ('zone3', 'Zone 3 — Dubai Marina, JBR, Palm Jumeirah, Bluewaters Island, Emirates Hills, Jumeirah Golf Estates, Dubai Sports City, Arabian Ranches, Damac Hills, Tilal Al Ghaf, The Springs, The Meadows, The Lakes'), ('zone4', 'Zone 4 — Dubai South, Expo City, Al Furjan, Jebel Ali, Dubai Investment Park (DIP), The Villa, Mudon, Town Square, Arabian Ranches 2 & 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clientpackage',
            name='package_type',
            field=models.CharField(choices=[('monthly_wellness', 'Rosette Wellness Membership'), ('vip_wellness', 'Rosette Signature Membership')], max_length=20),
        ),
    ]
