# Generated by Django 6.0.6 on 2026-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_alter_appointment_service_alter_appointment_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 minutes'), (60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('signature', 'Signature Full Body Reset'), ('swedish', 'Swedish Massage'), ('deep_tissue', 'Deep Tissue Massage'), ('sports', 'Sports Massage'), ('hot_stone', 'Hot Stone Massage'), ('foot_massage', 'Foot Massage'), ('head_neck_shoulders', 'Head, Neck & Shoulders'), ('monthly_wellness', 'Rosette Wellness Membership'), ('vip_wellness', 'Rosette Signature Membership')], max_length=20),
        ),
    ]
