# Generated by Django 6.0.6 on 2026-07-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='addon',
            field=models.CharField(choices=[('none', 'No Add-On'), ('foot_30', 'Foot Massage — 30 min (140 AED)'), ('extra_30', '30 Minutes Extra (120 AED)')], default='none', max_length=20),
        ),
    ]
