# Generated by Django 6.0.6 on 2026-09-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_alter_appointment_addon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('appointment_date', 'appointment_time')},
        ),
        migrations.AlterModelOptions(
            name='clientpackage',
            options={'ordering': ('-purchase_date',)},
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_focus_area',
            field=models.TextField(blank=True, null=True),
        ),
    ]
